<?php require('template/header.phtml') ?>
    <body>
    <div>
        <h3>Log In</h3>
        <form name="loginForm" method="post" action="login.php">
            <label>Email: </label>
            <input type="text" name="email">
            <br/>
            <label>Password: </label>
            <input type="text" name="password">

            <input type="submit" name="Submit" value-="Submit">

        </form>
    </div>
    </body>


<?php require('template/footer.phtml') ?>