<?php require('template/header.phtml') ?>
    <div class="row">
        <div class="col-md-12">
            <h3>Log In</h3>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12 col-sx-12 col-sm-12">
            <form name="loginForm" method="post" action="login.php" class="form">
                <div class="form-group">
                    <label for="email">Email: </label>
                    <input type="text" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label or="password">Password:</label>
                    <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group">
                    <input type="submit" name="Submit" value-="Submit" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
<?php require('template/footer.phtml') ?>