<?php require('template/header.phtml') ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-sx-12">
            <h3>Register Here</h3>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-sx-12">
            <form name="registerForm" method="post" action="register.php" class="form">
                <div class="form-group">
                    <label for="email">Email: </label>
                    <input type="text" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">Password: </label>
                    <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group">
                    <label for="confirmPassword">Confirm Password: </label>
                    <input type="password" name="confirmPassword" class="form-control">
                </div>
                <div class="form-group">
                    <label for="address">Address: </label>
                    <input type="text" name="address" class="form-control">
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number: </label>
                    <input type="text" name="phone" class="form-control">
                </div>
                <div class="form-group">
                    <input type="submit" name="Submit" value="Submit" class="btn btn-success">
                    <input type="reset" name="Reset" value="Reset" class="btn btn-danger">
                </div>
            </form>
        </div>
    </div>
<?php require('template/footer.phtml') ?>
