<?php require ('template/header.phtml') ?>

    <h1>Search CD</h1>
    <form name="searchForm" method="post" action="searchCD.php">
        <label>Search </label>
        <br/>
        <input type="submit" name="Submit" value="Submit">
        <input type="text" name="searchInput">
    </form>
    <?php if(isset($view->CDs)){ ?>
    <table style="100%">
        <tr>
            <th></th>
            <th>CD Title</th>
            <th>Artist</th>
            <th>Release Date</th>
            <th>Genre</th>
            <th>Price</th>
            <th>Status</th>
            <th>CDID</th>
        </tr>
        <?php foreach ($view->CDs as $CD) { ?>

            <tr>
                <td><img src="images/<?php echo $CD['image']; ?>" alt="Cover" style="width:140px;height:180px;"></td>
                <td><?php echo $CD['title']; ?></td>
                <td><?php echo $CD['artist']; ?></td>
                <td><?php echo $CD['release']; ?></td>
                <td><?php echo $CD['genre']; ?></td>
                <td><?php echo $CD['price']; ?></td>
                <td><?php if ($CD['status'] == 0) echo 'Available'; else echo 'Rented'; ?></td>
                <td><?php echo $CD['CDid']; ?></td>
                <?php if (isset($_SESSION['userID'])) { ?>
                    <td><a href="selectedCD.php?id=<?php echo $CD['CDid']; ?>" class="button">Rent</a></td>
                <?php } else {?>
                    <td> please log in to rent</td>
                <?php } ?>
            </tr>
        <?php }
    } ?>

    </table>


<?php require ('template/footer.phtml')?>