<?php require('template/header.phtml') ?>

    <h1>Selected CD</h1>
    <table style="100%">
        <tr>
            <th></th>
            <th>CD Title</th>
            <th>Artist</th>
            <th>Release Date</th>
            <th>Genre</th>
            <th>Price</th>
            <th>Status</th>
            <th>CD ID</th>

        </tr>


    </table>


<?php require('template/footer.phtml') ?>