    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <?php if (isset($_SESSION['userID'])) { ?>

                <li> logged in as : <?php echo ($_SESSION['email']) ?></li>
            <?php } else {?>
                <li><a href="login.php">Log In</a></li>

            <?php } ?>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>