<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role=""document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/new_uos_logo.jpg" alt="Salford University" />
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>

            </div>
        </div>


    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
        <ul class="nav navbar_default nav-stacked">
            <li><a href="index.php">Home</a></li>
            <li><a href="allCDs.php">All Cds</a></li>
            <li><a href="searchCD.php">Search CD</a></li>
            <?php if (isset($_SESSION['userID'])) { ?>
                <li><a href="logout.php">Logout</a></li>
                <li><?php echo ($_SESSION['userID']) ?></li>
            <?php } else {?>
                <li><a href="login.php">Log In</a></li>
                <li><a href="register.php">Register</a></li>
            <?php } ?>

        </ul>
       </div>

    <div id="content" class="col-xs-6 col-sm-9 col-md-10">



